<a href="https://colab.research.google.com/github/rajan5639/pw_data_science/blob/main/2_Numpy_advance_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.zeros(5) #Return a new array of given shape and type, filled with zeros.

In [ ]:
a.ndim

1

In [ ]:
a

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
b = np.zeros((3, 4))

In [ ]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b.ndim

2

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(5, dtype=int) #Return a new array of given shape and type, filled with ones

array([1, 1, 1, 1, 1])

In [ ]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.twos(5) #doesn't exist in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.array([[2, 2, 2,], [2, 2, 2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [ ]:
arr = np.zeros((3, 4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr.ndim

2

In [ ]:
#3 dimensionaly array
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr = np.zeros((3, 3, 4))

In [ ]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr.ndim

3

In [ ]:
np.zeros((1, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
b = np.zeros((1, 1, 3, 3))

In [ ]:
b

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [ ]:
b.ndim

4

In [ ]:
c = np.zeros((1, 1, 1, 3, 3))

In [ ]:
c

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]]])

In [ ]:
c.ndim

5

In [ ]:
arr = np.zeros((3, 4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a = arr+5

In [ ]:
a * 2

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [ ]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a - 1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.empty((3, 4)) #Return a new array of given shape and type, without initializing entries.It means entries in the array can be anything random values

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
#optional>> random module
import random
random.choice((1, 2, 3, 4, 5))

2

In [ ]:
random.choice("Ajay")

'j'

In [ ]:
random.randrange(1, 10)

8

In [ ]:
random.random() #a random no generated between 0(included) and 1(excluded)

0.9728985682750961

In [ ]:
lis = [1, 2, 3, 4, 5]
lis

[1, 2, 3, 4, 5]

In [ ]:
random.shuffle(lis)

In [ ]:
lis

[5, 4, 2, 3, 1]

In [ ]:
random.uniform(7, 14)

12.576954563249108

In [ ]:
#random numbers related concept in numpy

np.array([])

array([], dtype=float64)

In [ ]:
np.random.random_sample()

0.7168659820559915

In [ ]:
np.random.random_sample((5, )) #1 dim array of 5 random nos

array([0.85743581, 0.28005044, 0.48774049, 0.10342411, 0.41707208])

In [ ]:
np.random.rand(1)

array([0.39270155])

In [ ]:
np.random.rand(2, 3)

array([[0.29561722, 0.23591216, 0.76403335],
       [0.53960614, 0.22486023, 0.26366914]])

In [ ]:
np.random.randn(2, 3) #return a sample (or samples) from the "standard normal" distribution.

array([[ 0.52726285,  0.45931722,  0.24064425],
       [-0.83145839,  0.13407456,  0.11095632]])

In [ ]:
np.random.randint(1, 5, size = (3, 4)) #start from 1 and end at 5-1 and give array of shape 3, 4

array([[2, 4, 3, 1],
       [4, 2, 1, 1],
       [4, 1, 4, 1]])

In [ ]:
arr = np.random.randint(1, 5, size = (3, 4))

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.size

12

In [ ]:
arr

array([[2, 1, 1, 4],
       [2, 3, 2, 3],
       [4, 3, 3, 1]])

In [ ]:
#reshaping of array
arr1 = arr.reshape(2, 6) #Returns an array containing the same data with a new shape.

In [ ]:
arr1

array([[2, 1, 1, 4, 2, 3],
       [2, 3, 4, 3, 3, 1]])

In [ ]:
arr1.size

12

In [ ]:
arr1.shape

(2, 6)

In [ ]:
arr1.ndim

2

In [ ]:
#array size will never change, always reshape parameter should be multiplication of original array size

In [ ]:
arr

array([[2, 1, 1, 4],
       [2, 3, 2, 3],
       [4, 3, 3, 1]])

In [ ]:
arr.reshape(3,2)

ValueError: cannot reshape array of size 12 into shape (3,2)

In [ ]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [ ]:
arr.reshape(3,4)

array([[2, 1, 1, 4],
       [2, 3, 2, 3],
       [4, 3, 3, 1]])

In [ ]:
arr.reshape(4,3)

array([[2, 1, 1],
       [4, 2, 3],
       [2, 3, 4],
       [3, 3, 1]])

In [ ]:
arr.reshape(1, 12)

array([[2, 1, 1, 4, 2, 3, 2, 3, 4, 3, 3, 1]])

In [ ]:
arr.reshape(12, 1)

array([[2],
       [1],
       [1],
       [4],
       [2],
       [3],
       [2],
       [3],
       [4],
       [3],
       [3],
       [1]])

In [ ]:
#case when you dont know in reshape what should be the row or column count
#use any negative value for rows or columns
arr.reshape(4,-1)

array([[2, 1, 1],
       [4, 2, 3],
       [2, 3, 4],
       [3, 3, 1]])

In [ ]:
arr.reshape(4,-100)

array([[2, 1, 1],
       [4, 2, 3],
       [2, 3, 4],
       [3, 3, 1]])

In [ ]:
arr.reshape(-1,4)

array([[2, 1, 1, 4],
       [2, 3, 2, 3],
       [4, 3, 3, 1]])

In [ ]:
arr

array([[2, 1, 1, 4],
       [2, 3, 2, 3],
       [4, 3, 3, 1]])

In [ ]:
arr.reshape(12, 1).base #to see the original array

array([[2, 1, 1, 4],
       [2, 3, 2, 3],
       [4, 3, 3, 1]])

In [ ]:
arr.reshape(2, 2, 3) #multiplication should be equals to arr size

array([[[2, 1, 1],
        [4, 2, 3]],

       [[2, 3, 4],
        [3, 3, 1]]])

In [ ]:
arr.reshape(1, 2, 2, 3)

array([[[[2, 1, 1],
         [4, 2, 3]],

        [[2, 3, 4],
         [3, 3, 1]]]])

In [ ]:
arr.reshape(1, 2, 2, 3).ndim

4

In [ ]:
arr.reshape(4, 3, 1) #3 rows 1 column repeated 4 times in the third dimension

array([[[2],
        [1],
        [1]],

       [[4],
        [2],
        [3]],

       [[2],
        [3],
        [4]],

       [[3],
        [3],
        [1]]])

In [ ]:
#conditions on array
arr1=np.random.randint(1, 10, (5, 6))

In [ ]:
arr1

array([[4, 9, 2, 5, 2, 2],
       [4, 7, 3, 7, 8, 6],
       [4, 4, 5, 8, 8, 3],
       [7, 8, 3, 7, 9, 8],
       [3, 6, 1, 7, 5, 4]])

In [ ]:
arr1.shape

(5, 6)

In [ ]:
arr1.size

30

In [ ]:
arr1.ndim

2

In [ ]:
arr1

array([[4, 9, 2, 5, 2, 2],
       [4, 7, 3, 7, 8, 6],
       [4, 4, 5, 8, 8, 3],
       [7, 8, 3, 7, 9, 8],
       [3, 6, 1, 7, 5, 4]])

In [ ]:
arr1 > 3

array([[ True,  True, False,  True, False, False],
       [ True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True, False],
       [ True,  True, False,  True,  True,  True],
       [False,  True, False,  True,  True,  True]])

In [ ]:
arr1[arr1 > 3] #select all the elements of arr1 where the condition is true

array([4, 9, 5, 4, 7, 7, 8, 6, 4, 4, 5, 8, 8, 7, 8, 7, 9, 8, 6, 7, 5, 4])

In [ ]:
arr1[arr1 < 3]

array([2, 2, 2, 1])

In [ ]:
arr1

array([[4, 9, 2, 5, 2, 2],
       [4, 7, 3, 7, 8, 6],
       [4, 4, 5, 8, 8, 3],
       [7, 8, 3, 7, 9, 8],
       [3, 6, 1, 7, 5, 4]])

In [ ]:
#to access elements in an arry

In [ ]:
arr1[0]

array([4, 9, 2, 5, 2, 2])

In [ ]:
arr1[1][2]

3

In [ ]:
arr1

array([[4, 9, 2, 5, 2, 2],
       [4, 7, 3, 7, 8, 6],
       [4, 4, 5, 8, 8, 3],
       [7, 8, 3, 7, 9, 8],
       [3, 6, 1, 7, 5, 4]])

In [ ]:
arr1[3][1]

8

In [ ]:
arr1

array([[4, 9, 2, 5, 2, 2],
       [4, 7, 3, 7, 8, 6],
       [4, 4, 5, 8, 8, 3],
       [7, 8, 3, 7, 9, 8],
       [3, 6, 1, 7, 5, 4]])

In [ ]:
#from oth row to 2nd row
arr1[0:3]

array([[4, 9, 2, 5, 2, 2],
       [4, 7, 3, 7, 8, 6],
       [4, 4, 5, 8, 8, 3]])

In [ ]:
#0 to 2nd row and 0th and 2nd column
arr1[0:3,[0, 2] ]

array([[4, 2],
       [4, 3],
       [4, 5]])

In [ ]:
#slicing on both rows and columns together
arr1

array([[4, 9, 2, 5, 2, 2],
       [4, 7, 3, 7, 8, 6],
       [4, 4, 5, 8, 8, 3],
       [7, 8, 3, 7, 9, 8],
       [3, 6, 1, 7, 5, 4]])

In [ ]:
arr1[0:3, 1:3]

array([[9, 2],
       [7, 3],
       [4, 5]])

In [ ]:
arr1[0:3, [0, 1]]

array([[4, 9],
       [4, 7],
       [4, 4]])

In [ ]:
arr1[0, [1, 3]]

array([9, 5])

In [ ]:
arr1[2:4, [0, 3]]

array([[4, 8],
       [7, 7]])

In [ ]:
arr1[2:5]

array([[4, 4, 5, 8, 8, 3],
       [7, 8, 3, 7, 9, 8],
       [3, 6, 1, 7, 5, 4]])

In [ ]:
arr1[2:5, 0:2]

array([[4, 4],
       [7, 8],
       [3, 6]])

In [ ]:
#mathematical operations on two arrays
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [ ]:
arr1

array([[2, 1, 2],
       [1, 1, 1],
       [1, 2, 2]])

In [ ]:
arr2

array([[1, 1, 2],
       [1, 1, 2],
       [2, 2, 2]])

In [ ]:
arr1+arr2 #indexwise element addition

array([[3, 2, 4],
       [2, 2, 3],
       [3, 4, 4]])

In [ ]:
arr1-arr2

array([[ 1,  0,  0],
       [ 0,  0, -1],
       [-1,  0,  0]])

In [ ]:
arr1 * arr2 #index wise multiplication

array([[2, 1, 4],
       [1, 1, 2],
       [2, 4, 4]])

In [ ]:
arr1, arr2

(array([[2, 1, 2],
        [1, 1, 1],
        [1, 2, 2]]),
 array([[1, 1, 2],
        [1, 1, 2],
        [2, 2, 2]]))

In [ ]:
arr1/arr2 #index wise divison

array([[2. , 1. , 1. ],
       [1. , 1. , 0.5],
       [0.5, 1. , 1. ]])

In [ ]:
4/0

ZeroDivisionError: division by zero

In [ ]:
arr1/0

/tmp/ipykernel_525/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
arr1

array([[2, 1, 2],
       [1, 1, 1],
       [1, 2, 2]])

In [ ]:
#matrix multiplication >>matrix is a specialised 2-d array
#matrix multiplication is different from index wise multiplication

In [ ]:
arr1 @ arr2

array([[ 7,  7, 10],
       [ 4,  4,  6],
       [ 7,  7, 10]])

In [ ]:
np.dot(arr1, arr2) #another way of matrix multiplication

array([[ 7,  7, 10],
       [ 4,  4,  6],
       [ 7,  7, 10]])

In [ ]:
arr1 * arr2

array([[2, 1, 4],
       [1, 1, 2],
       [2, 4, 4]])

In [ ]:
#broadcasting

In [ ]:
arr = np.zeros((3, 4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
a = np.array([[1, 2, 3, 4]])

In [ ]:
#Transpose>> converting rows to columns and columns to rows

In [ ]:
a

array([[1, 2, 3, 4]])

In [ ]:
a.T

array([1, 2, 3, 4])