<a href="https://colab.research.google.com/github/rajan5639/pw_data_science/blob/main/3_Numpy_advance_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [ ]:
arr2

array([[2, 1, 2],
       [1, 1, 1],
       [2, 2, 1]])

In [ ]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [1]:
arr1.flatten() #Return a copy of the array collapsed into one dimension.

NameError: name 'arr1' is not defined

In [ ]:
#expand dimension
arr = np.array([1, 2, 3, 4])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr.ndim

1

In [ ]:
np.expand_dims(arr, axis=0) #increase the dimension by 1 in the provided axis, 0 means rows(x axis), 1 means column wise(y axis)

array([[1, 2, 3, 4]])

In [ ]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
np.expand_dims(arr, axis=1).ndim

2

In [ ]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.expand_dims(arr, axis = 0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.expand_dims(arr, axis = 0).ndim

3

In [ ]:
np.expand_dims(arr, axis = 1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [ ]:
np.expand_dims(arr, axis = 0).ndim

3

In [ ]:
a = np.array([[1], [2], [3]])

In [ ]:
a

array([[1],
       [2],
       [3]])

In [ ]:
a.ndim

2

In [ ]:
#squeezing the dimension by 1 dimension
np.squeeze(a)#Remove axes of length one from `a`

array([1, 2, 3])

In [ ]:
a

array([[1],
       [2],
       [3]])

In [ ]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [ ]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [ ]:
np.repeat(arr1, 2)

array([2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1])

In [ ]:
np.repeat(arr1, 2, axis=0)

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [ ]:
np.repeat(arr2, 3, axis=0)

array([[2, 1, 2],
       [2, 1, 2],
       [2, 1, 2],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [ ]:
np.repeat(arr2, 3, axis=1)

array([[2, 2, 2, 1, 1, 1, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 1, 1, 1]])

In [ ]:
a

array([[1],
       [2],
       [3]])

In [ ]:
np.roll(a, -1) #shift place

array([[2],
       [3],
       [1]])

In [ ]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [ ]:
c = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

In [ ]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.roll(c, -1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [ ]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.roll(c, 2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.roll(c, 2, axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [ ]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [ ]:
arr2

array([[2, 1, 2],
       [1, 1, 1],
       [2, 2, 1]])

In [ ]:
arr1+arr2

array([[4, 3, 3],
       [3, 3, 2],
       [4, 4, 2]])

In [ ]:
arr1-arr2

array([[ 0,  1, -1],
       [ 1,  1,  0],
       [ 0,  0,  0]])

In [ ]:
arr1 * arr2

array([[4, 2, 2],
       [2, 2, 1],
       [4, 4, 1]])

In [ ]:
arr1 > arr2

array([[False,  True, False],
       [ True,  True, False],
       [False, False, False]])

In [ ]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [ ]:
~arr1

array([[-3, -3, -2],
       [-3, -3, -2],
       [-3, -3, -2]])

In [ ]:
#operations on numpy string array

d = np.array(["pw", "skills"])

In [ ]:
d

array(['pw', 'skills'], dtype='<U6')

In [ ]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [ ]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [ ]:
#mathematical function

In [ ]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [ ]:
np.sin(arr1)

array([[0.90929743, 0.90929743, 0.84147098],
       [0.90929743, 0.90929743, 0.84147098],
       [0.90929743, 0.90929743, 0.84147098]])

In [ ]:
np.cos(arr1)

array([[-0.41614684, -0.41614684,  0.54030231],
       [-0.41614684, -0.41614684,  0.54030231],
       [-0.41614684, -0.41614684,  0.54030231]])

In [ ]:
np.tan(arr1)

array([[-2.18503986, -2.18503986,  1.55740772],
       [-2.18503986, -2.18503986,  1.55740772],
       [-2.18503986, -2.18503986,  1.55740772]])

In [ ]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.     ],
       [0.30103, 0.30103, 0.     ],
       [0.30103, 0.30103, 0.     ]])

In [ ]:
np.exp(arr1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183]])

In [ ]:
np.power(arr1, 3)

array([[8, 8, 1],
       [8, 8, 1],
       [8, 8, 1]])

In [ ]:
np.max(arr1)

2

In [ ]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [ ]:
np.mean(arr1)

1.6666666666666667

In [ ]:
np.min(arr1)

1

In [ ]:
np.std(arr1)

0.4714045207910317

In [ ]:
np.var(arr1)

0.2222222222222222

In [ ]:
arr1-arr2

array([[ 0,  1, -1],
       [ 1,  1,  0],
       [ 0,  0,  0]])

In [ ]:
np.subtract(arr1, arr2)

array([[ 0,  1, -1],
       [ 1,  1,  0],
       [ 0,  0,  0]])

In [ ]:
arr1*arr2

array([[4, 2, 2],
       [2, 2, 1],
       [4, 4, 1]])

In [ ]:
np.multiply(arr1, arr2)

array([[4, 2, 2],
       [2, 2, 1],
       [4, 4, 1]])

In [ ]:
np.mod(arr1, arr2) #return element wise remainder

array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.        ]])

In [ ]:
#sorting and searching in numpy array
e = np.array([5, 6, 1, 2])

In [ ]:
e

array([5, 6, 1, 2])

In [ ]:
np.sort(e) #Return a sorted copy of an array.

array([1, 2, 5, 6])

In [ ]:
f = np.array([5, 199, 200, 6, 7, 8])
f

array([  5, 199, 200,   6,   7,   8])

In [ ]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [ ]:
np.searchsorted(f, 170) #Find indices where elements should be inserted to maintain order.

6

In [ ]:
f = np.array([5, 199, 200,0, 0, 0, 0, 6, 7, 8])
f

array([  5, 199, 200,   0,   0,   0,   0,   6,   7,   8])

In [ ]:
np.count_nonzero(f)

6

In [ ]:
f[f>0]

array([  5, 199, 200,   6,   7,   8])

In [ ]:
np.where(f>0) #same as above condition

(array([0, 1, 2, 7, 8, 9]),)

In [ ]:
np.extract(f>0, f) #same as above condition

array([  5, 199, 200,   6,   7,   8])

In [ ]:
f

array([  5, 199, 200,   0,   0,   0,   0,   6,   7,   8])

In [ ]:
f.byteswap() #Swap the bytes of the array elements

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
                          0,                    0,                    0,
                          0,   432345564227567616,   504403158265495552,
         576460752303423488])

In [ ]:
import numpy.matlib as nm
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#numpy linear algebra(optonal)

In [ ]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [ ]:
arr2

array([[2, 1, 2],
       [1, 1, 1],
       [2, 2, 1]])

In [ ]:
arr1@arr2

array([[8, 6, 7],
       [8, 6, 7],
       [8, 6, 7]])

In [ ]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [ ]:
np.linalg.det(arr1)

0.0

In [ ]:
np.linalg.det(arr2)

-1.0

In [ ]:
#in matrix you can not devide by another matrix, you have inverse
np.linalg.inv(arr2)

array([[ 1., -3.,  1.],
       [-1.,  2.,  0.],
       [ 0.,  2., -1.]])

In [ ]:
a = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [ ]:
b = np.array([16, 8, 0])

In [ ]:
np.linalg.solve(a, b)

array([2.59630607, 0.84432718, 2.21635884])